name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check_x86:
    name: Check (x86)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make -j$(nproc)

      - name: Test
        run: make run-tests -j$(nproc)

      - name: Format
        run: make fmt-check

  check_aarch64:
    name: Check (aarch64)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make -j$(nproc)

      - name: Test
        run: make run-tests -j$(nproc)

      - name: Format
        run: make fmt-check
